### ISSUE TITLE
Error: resource not found

### ISSUE THREAD

**Issue by saadhana** [skrede/kuka_gazebo#1]
catkin build is successful but running 

> roslaunch kuka_gazebo kr6_r900sixx_gazebo_joint_control.launch

gives the following error: 

> 

resource not found: kuka_resources
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/asyin/catkin_ws/src/kuka_gazebo
ROS path [2]=/opt/ros/melodic/share
when processing file: /home/asyin/catkin_ws/src/kuka_gazebo/kuka_kr6_r900sixx/urdf/kr6r900sixx_macro.xacro
included from: /home/asyin/catkin_ws/src/kuka_gazebo/kuka_kr6_r900sixx/urdf/kuka_kr6r900sixx_macro.xacro
included from: /home/asyin/catkin_ws/src/kuka_gazebo/kuka_kr6_r900sixx/urdf/kuka_kr6r900sixx.xacro
RLException: while processing /home/asyin/catkin_ws/src/kuka_gazebo/kuka_kr6_r900sixx/launch/gazebo_load.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/melodic/lib/xacro/xacro '/home/asyin/catkin_ws/src/kuka_gazebo/kuka_kr6_r900sixx/urdf/kuka_kr6r900sixx.xacro'] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro '$(find kuka_gazebo)/kuka_kr6_r900sixx/urdf/kuka_kr6r900sixx.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file

>

**Comment by skrede** [comment]
You'll need to download the kuka_experimental metapackage as well. You can find them [here](https://github.com/ros-industrial/kuka_experimental). Clone this repository to `/home/asyin/catkin_ws/src/`, for example.
